import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Loose Sugar',
      slug: 'sugar-loose',
      category: 'Sugar',
      image: '/images/p1.jpg',
      price: 37,
      countInStock: 20,
      brand: 'KM',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality sugar product',
    },
    {
      //_id: '2',
      name: 'Sugar',
      slug: 'sugar',
      category: 'Sugar',
      image: '/images/p2.jpg',
      price: 39,
      countInStock: 0,
      brand: 'MR.K',
      rating: 4.3,
      numReviews: 10,
      description: 'high quality sugar',
    },
    {
      //_id: '3',
      name: "Parry's Sugar",
      slug: 'sugar-parry',
      category: 'Sugar',
      image: '/images/p3.jpg',
      price: 40,
      countInStock: 20,
      brand: 'E.I.D. Parry (India) Limited',
      rating: 4.5,
      numReviews: 10,
      description: 'quality sugar',
    },
    {
      //_id: '4',
      name: 'Sambar Masala',
      slug: 'spices-dd',
      category: 'Spices',
      image: '/images/p4.jpg',
      price: 41,
      countInStock: 20,
      brand: 'DD',
      rating: 3,
      numReviews: 10,
      description: 'high quality',
    },
  ],
};

export default data;
