const data = {
  products: [
    {
      name: 'Loose Sugar',
      slug: 'sugar-loose',
      category: 'Sugar',
      image: '/images/p1.jpg',
      price: 37,
      countInStock: 20,
      brand: 'KM',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality sugar product',
    },
    {
      name: 'Sugar',
      slug: 'sugar',
      category: 'Sugar',
      image: '/images/p2.jpg',
      price: 39,
      countInStock: 20,
      brand: 'MR.K',
      rating: 4.3,
      numReviews: 10,
      description: 'high quality sugar',
    },
    {
      name: "Parry's Sugar",
      slug: 'sugar-parry',
      category: 'Sugar',
      image: '/images/p3.jpg',
      price: 40,
      countInStock: 20,
      brand: 'E.I.D. Parry (India) Limited',
      rating: 4.5,
      numReviews: 10,
      description: 'quality sugar',
    },
    {
      name: 'DD Sugar',
      slug: 'sugar-dd',
      category: 'Sugar',
      image: '/images/p4.jpg',
      price: 41,
      countInStock: 20,
      brand: 'DD',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality',
    },
  ],
};

export default data;
